# Generated by Django 5.1.5 on 2025-01-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Ник персонажа')),
                ('haddan_id', models.IntegerField(verbose_name='ID персонажа')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(verbose_name='S/N вещи')),
                ('item_type', models.CharField(max_length=50, verbose_name='Тип шмотки')),
                ('article', models.SmallIntegerField(verbose_name='Артикул шмотки')),
                ('href', models.URLField(verbose_name='Ссылка на шмотку')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'ordering': ('item_type',),
            },
        ),
        migrations.CreateModel(
            name='GamerWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamers', to='items.gamer', verbose_name='Игрок')),
                ('wear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wears', to='items.wear', verbose_name='Вещь игрока')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ('gamer',),
            },
        ),
    ]
