# Generated by Django 5.1.5 on 2025-01-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wear',
            name='gamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gamers', to='items.gamer', verbose_name='Игрок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wear',
            name='item_id',
            field=models.IntegerField(unique=True, verbose_name='S/N вещи'),
        ),
        migrations.DeleteModel(
            name='GamerWear',
        ),
    ]
