# Generated by Django 5.1.5 on 2025-01-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_wear_gamer_alter_wear_item_id_delete_gamerwear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='haddan_id',
            field=models.IntegerField(unique=True, verbose_name='ID персонажа'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Ник персонажа'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.gamer', verbose_name='Игрок'),
        ),
        migrations.CreateModel(
            name='GamerWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamers', to='items.gamer', verbose_name='Игрок')),
                ('wear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wears', to='items.wear', verbose_name='Вещь игрока')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ('gamer',),
            },
        ),
    ]
