# Generated by Django 4.2.16 on 2024-10-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер спринта')),
                ('topic', models.CharField(max_length=256, verbose_name='Тема')),
                ('lesson', models.IntegerField(verbose_name='Номер урока')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('crib', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
