# Generated by Django 4.2.16 on 2024-10-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер спринта')),
                ('topic', models.CharField(max_length=256, verbose_name='Тема')),
                ('lesson', models.IntegerField(verbose_name='Номер урока')),
            ],
        ),
        migrations.RemoveField(
            model_name='crib',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='crib',
            name='number',
        ),
        migrations.RemoveField(
            model_name='crib',
            name='topic',
        ),
    ]
