# Generated by Django 4.2.16 on 2024-10-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0003_crib_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crib',
            options={'verbose_name': 'Шпора', 'verbose_name_plural': 'Шпоры'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='number',
            new_name='sprint_number',
        ),
    ]
