# Generated by Django 4.2.16 on 2024-10-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0004_alter_crib_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='lesson_number',
        ),
    ]
