# Generated by Django 4.2.16 on 2024-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0005_rename_lesson_lesson_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crib',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
