# Generated by Django 4.2.16 on 2024-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0006_alter_crib_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crib',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
