# Generated by Django 4.2.16 on 2024-10-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0007_alter_crib_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sprint_name',
            field=models.CharField(default=1, max_length=256, verbose_name='Название спринта'),
            preserve_default=False,
        ),
    ]
