# Generated by Django 4.2.16 on 2024-10-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cribs', '0008_lesson_sprint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crib',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='cribs.lesson', verbose_name='Урок'),
        ),
    ]
